### ISSUE TITLE
[ROIs2Regions.m] x-y swapped and unnecessary +1?

### ISSUE THREAD

**Issue by gkhtnk** [DylanMuir/ReadImageJROI#1]
Hi Dylan
Thank you for your useful tools.

**It seems ROIs2Regions.m have bugs around handling x-y coordinates.**

I tried to visualize my ('freehand') ROI data with the code below.
But it shows "fragmented" ROIs.

```Matlab
cvsROI = ReadImageJROI('RoiSet.zip');
sRegions = ROIs2Regions(cvsROI , vnImageSize);
mnLabelMatrix = labelmatrix(sRegions);
imagesc(label2rgb(mnLabelMatrix));
```

I checked ROIs2Regions.m and found 2 points.

---

**[1]  x-y was wrongly swapped.**

ROIs2Regions apply transpose (`'`) to the `mbThisMask`.
That will cause swapping of x and y dimension.

```Matlab
   sRegions.PixelIdxList{nROIIndex} = find(mbThisMask');
```

So I think it should be removed.

```Matlab
   sRegions.PixelIdxList{nROIIndex} = find(mbThisMask);
```

With this change, the ROI shape in `mnLabelMatrix` looks correct.

---

**[2] Unnecessary +1**

Additional validation, I compared the result with the image manually output from ImageJ.
I applied "Fill" to background and ROI with two different colors.
For background: Edit > Fill
For ROI: ROI Manager > More > Fill

```Matlab
mnImageJBinary= imread('Sample_ImageJ_Binary.tif');
imshowpair(mnImageJBinary>0, mnLabelMatrix>0);
```

And found that there is a shift between 2 images.

I guess that the addition of "1" to mnCoordinates is not necessary.

```Matlab
mbThisMask = poly2mask(sThisROI.mnCoordinates(:, 1)+1, sThisROI.mnCoordinates(:, 2)+1, vnImageSize(1), vnImageSize(2));
```

So it should be like below.

```Matlab
mbThisMask = poly2mask(sThisROI.mnCoordinates(:, 1), sThisROI.mnCoordinates(:, 2), vnImageSize(1), vnImageSize(2));
```

---

With editing these 2 points, ROIs2Regions.m works well for "Freehand" ROI in my environment.
I did not check for other cases "rectangle", "oval", "polygon".

First of all, I want to know this is generally happening or caused by my environment or somehow my misunderstanding.

My environment for this issue is below.
Matlab:  2019a
ImageJ: 1.52v on Fiji

Best,
Gaku

**Comment by DylanMuir** [comment]
Hi Gaku

Sorry for my slow reply. Both of these points you mention are to deal with differences between the way MATLAB deals with images and the way ImageJ deals with images. The intention is that if you load an image into MATLAB (`imread` or similar), and use `ROIs2Regions`, that the ROIs in MATLAB match the same pixels on the image as the ROIs in ImageJ.

Matlab begins indexing from `1` instead of `0`, hence the `+1`.

Matlab indexes matrices as (`row, col`), which is (`y, x`) for images — hence the transposition.
